version: '3.8'
services:
  mysql:
    container_name: rails_tutorial_database
    image: mysql:8.0.30
    volumes:
      - mysql:/var/lib/mysql
      - ./db/init/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rails_tutorial
  api:
    container_name: rails_tutorial_api
    command: 
      [ "bash", "-c", "rm -f tmp/pids/server.pid; RAILS_ENV=development bundle exec rails s -b 0.0.0.0" ]
    build:
      context: .
    volumes:
      - .:/work:cached
      - ./db:/work/db
    environment:
      - MYSQL_HOST_NAME=mysql
      - MYSQL_PASSWORD=root
    ports:
      - 3000:3000
    depends_on:
      - mysql
volumes:
  mysql:
