default: &default
  adapter: mysql2
  encoding: utf8mb4
  database: rails_tutorial
  pool: 5
  # socket: /tmp/mysql.sock

development:
  <<: *default
  host: <%= ENV['MYSQL_HOST_NAME'] %> 
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] %>

test:
  <<: *default
  host: <%= ENV['MYSQL_HOST_NAME'] %> 
  username: root
  password: <%= ENV['MYSQL_PASSWORD'] %>
  database: rails_tutorial_test

production:
  <<: *default
  host: <%= ENV['MYSQL_HOST_NAME'] %> 
  username: rails
  password: <%= ENV['MYSQL_PASSWORD'] %>
